<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rest_reserve_sub_ext"
 *
 * Auto generated by Extension Builder 2018-12-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Reservierung Sub Ext',
    'description' => 'Regelt das Hochladen der Reservierungen und Subscription an die Datenbank',
    'category' => 'plugin',
    'author' => 'Paul Luding',
    'author_email' => 'luding@webit.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
